import { createContext, useContext, useEffect, useState } from 'react';

const translations = {
  mn: {
    // ── Shared / nav ──────────────────────────────────────────
    dashboard: 'Хяналтын самбар',
    subjects: 'Хичээлүүд',
    addStudent: 'Сурагч нэмэх',
    manageTeachers: 'Багш удирдах',
    password: 'Нууц үг',
    changePassword: 'Нууц үг солих',
    logout: 'Гарах',
    menu: 'Цэс',
    appName: 'ЕБС Дүн Бүртгэл',
    appFullName: 'ЕБС Дүн Бүртгэлийн Систем',
    appSubtitle: 'Ерөнхий боловсролын сургууль',
    login: 'Нэвтрэх',
    teacherLogin: 'Багш нэвтрэх',
    studentGrades: 'Сурагч дүн харах',
    welcome: 'Тавтай морил!',
    loginHint: 'Имэйл болон нууц үгээ оруулна уу',
    email: 'Имэйл хаяг',
    passwordLabel: 'Нууц үг',
    loggingIn: 'Нэвтэрч байна...',
    registerPrompt: 'Бүртгэлгүй юу?',
    register: 'Бүртгүүлэх',
    orGoogle: 'эсвэл Google-ээр',
    studentLoginHint: 'Нэвтрэх мэдээллийг багшаасаа аваарай',
    loginError: 'Нэвтрэхэд алдаа гарлаа',
    googleError: 'Google нэвтрэлт амжилтгүй болсон',
    footer: 'Бүх эрх хуулиар хамгаалагдсан',
    langToggleLabel: 'Хэл солих',
    loginSideText: 'Сурагчдын дүн бүртгэлийн систем. Ангиар ангилах, дүн харах, графикаар дүн харуулах боломжтой.',
    pillGrades: 'Дүн бүртгэл',
    pillCharts: 'График',
    pillByClass: 'Ангиар харах',
    pillSecure: 'Аюулгүй',
    sideCopyright: '© 2024 ЕБС Систем',

    // ── Common / reused ───────────────────────────────────────
    back: 'Буцах',
    backArrow: '← Буцах',
    cancel: 'Болих',
    save: 'Хадгалах',
    saving: 'Хадгалж байна...',
    delete: 'Устгах',
    edit: 'Засах',
    details: 'Дэлгэрэнгүй',
    loadingData: 'Мэдээлэл уншиж байна...',
    subjectLabel: 'Хичээл',
    totalLabel: 'Нийт',
    letterLabel: 'Үсгэн',
    classLabel: 'Анги',
    allOption: 'Бүгд',
    nameLabel: 'Нэр',
    printLabel: 'Хэвлэх',
    genericError: 'Алдаа гарлаа',
    roleAdmin: 'Админ',
    roleTeacher: 'Багш',
    semesterOf: '{semester}-р улирал',
    thExam1: 'Ш1',
    thExam2: 'Ш2',
    thAttendance: 'Ирц',
    thIndependent: 'БД',
    exam1Full: 'Шалгалт 1',
    exam2Full: 'Шалгалт 2',
    attendanceFull: 'Ирц',
    independentFull: 'Бие даалт',
    subjectsCountUnit: 'хичээл',
    studentsCountUnit: 'сурагч',
    gradeExcellent: 'Тэрлэлт',
    gradeGood: 'Сайн',
    gradeAverage: 'Дунд',
    gradeFail: 'Хангалтгүй',

    // ── Dashboard ─────────────────────────────────────────────
    dash_subtitle: 'Сурагчдын дүн, статистик мэдээллийг харах',
    dash_totalStudents: 'Нийт сурагч',
    dash_avgScore: 'Дундаж дүн',
    dash_successRate: 'Сурлагын амжилт',
    dash_warning: 'Анхааруулга (60-аас доош)',
    dash_searchPlaceholder: 'Нэрээр хайх...',
    dash_classFilter: 'Анги:',
    dash_yearFilter: 'Жил:',
    dash_semesterFilter: 'Улирал:',
    dash_semester1: '1-р улирал',
    dash_semester2: '2-р улирал',
    dash_totalPill: 'Нийт:',
    dash_template: 'Загвар',
    dash_importExcel: 'Excel оруулах',
    dash_qualityChartTitle: 'Хичээл тус бүрийн сурлагын чанар (≥75 оноо авсан сурагчийн %)',
    dash_quality: 'Чанар',
    dash_noResultsFor: '"{search}" нэртэй сурагч олдсонгүй',
    dash_noStudents: 'Сурагч бүртгэгдээгүй байна',
    dash_tryOtherSearch: 'Өөр нэрийг хайж үзнэ үү.',
    dash_addHint: 'Шинэ сурагч нэмэхийн тулд дээд талын "Сурагч нэмэх" товч дарна уу.',
    dash_atRiskBanner: 'Дүн хангалтгүй — анхааруулга',
    dash_prevPage: '← Өмнөх',
    dash_nextPage: 'Дараах →',
    dash_deleteConfirm: '"{name}"-г устгах уу?',
    dash_deletedToast: '{name} устгагдлаа',
    dash_gradeSaved: 'Дүн амжилттай хадгалагдлаа',
    dash_saveError: 'Хадгалахад алдаа гарлаа',
    dash_templateDownloaded: 'Загвар файл татаж авлаа',
    dash_noDataInFile: 'Файлд өгөгдөл олдсонгүй',
    dash_importedCount: '{count} сурагч нэмэгдлээ',
    dash_importFailCount: ', {count} алдаа: {error}',
    dash_importNoneAdded: 'Нэмэгдсэнгүй — {error}',
    dash_fileReadError: 'Файл уншихад алдаа гарлаа',
    dash_excelDownloaded: 'Excel файл татаж авлаа',
    modal_subjectNameRequired: 'Хичээлийн нэр оруулна уу',
    modal_subjectExists: '"{name}" хичээл аль хэдийн байна',
    modal_newSubjectPlaceholder: 'Хичээлийн нэр',

    // ── AddStudent ────────────────────────────────────────────
    add_pageTitle: 'Шинэ сурагч бүртгэх',
    add_pageSubtitle: 'Сурагчийн мэдээлэл болон хичээлийн дүнгүүдийг оруулна уу',
    add_photo: 'Зураг',
    add_addPhoto: 'Зураг нэмэх',
    add_uploading: 'Оруулж байна...',
    add_lastName: 'Овог',
    add_firstName: 'Нэр',
    add_academicYear: 'Хичээлийн жил',
    add_semester: 'Улирал',
    add_gmail: 'Gmail хаяг',
    add_optional: '(заавал биш)',
    add_loginPassword: 'Нэвтрэх нууц үг',
    add_minChars: 'Дор хаяж 6 тэмдэгт',
    add_fullName: 'Бүтэн нэр:',
    add_gradesTitle: 'Хичээлийн дүнгүүд',
    add_avgTotalScore: 'Дундаж нийт оноо:',
    add_newSubjectPlaceholder: 'Шинэ хичээлийн нэр...',
    add_addSubjectBtn: '+ Хичээл нэмэх',
    add_registerBtn: 'Сурагч бүртгэх',
    add_subjectAlreadyAdded: 'Энэ хичээл аль хэдийн нэмэгдсэн байна',
    add_fileTooLarge: 'Файл 5MB-аас хэтэрч байна',
    add_photoReady: 'Зураг бэлэн боллоо',
    add_photoUploadError: 'Зураг оруулахад алдаа гарлаа',
    add_requiredFields: 'Овог, нэр болон ангийг оруулна уу!',
    add_atLeastOneSubject: 'Дор хаяж нэг хичээл нэмэх хэрэгтэй',
    add_registeredToast: '{name} амжилттай бүртгэгдлээ',
    add_registerError: 'Бүртгэхэд алдаа гарлаа',

    // ── StudentDetail ─────────────────────────────────────────
    detail_fetchError: 'Сурагчийн мэдээлэл авахад алдаа гарлаа',
    detail_loading: 'Сурагчийн мэдээлэл уншиж байна...',
    detail_deleteConfirm: 'Та "{name}"-ийг устгахдаа итгэлтэй байна уу? Энэ үйлдлийг буцаах боломжгүй.',
    detail_classPrefix: 'Анги:',
    detail_avgTotal: 'Дундаж нийт',
    detail_chartTitle: 'Хичээл тус бүрийн нийт дүн',
    detail_gradesDetailTitle: 'Дүнгийн дэлгэрэнгүй',
    detail_savingShort: 'Хадгалж...',
    detail_teacherSign: 'Багшийн гарын үсэг: ___________',
    detail_date: 'Огноо:',
    detail_printSchoolName: 'ЕБС ДҮН БҮРТГЭЛИЙН СИСТЕМ',
    detail_printReportTitle: 'ДҮНГИЙН ТАЙЛАН',
    detail_printAvg: 'Дундаж дүн:',
    detail_printYear: 'Хичээлийн жил:',
    detail_printAvgFooter: 'Дундаж нийт оноо:',

    // ── SubjectDashboard ──────────────────────────────────────
    subj_subtitle: 'Хичээл тус бүрийн дүнгийн статистик, график харьцуулалт',
    subj_totalSubjects: 'Нийт хичээл',
    subj_totalEntries: 'Нийт дүн оруулалт',
    subj_highestAvg: 'Хамгийн өндөр дундаж',
    subj_lowestAvg: 'Хамгийн бага дундаж',
    subj_sortBy: 'Эрэмбэлэх:',
    subj_sortAvg: 'Дундажаар',
    subj_sortName: 'Нэрээр',
    subj_sortCount: 'Сурагчийн тоогоор',
    subj_allClasses: 'Бүх анги',
    subj_noData: 'Хичээлийн мэдээлэл байхгүй байна',
    subj_noDataHint: 'Эхлээд сурагч болон дүнгийн мэдээлэл оруулна уу.',
    subj_excellentTitle: 'Тэрлэлт (≥90): {count}',
    subj_goodTitle: 'Сайн (75-89): {count}',
    subj_belowTitle: 'Дунд (<75): {count}',
    subj_excellentLabel: 'тэрлэлт',
    subj_goodLabel: 'сайн',
    subj_belowLabel: 'дунд',
    subj_studentsLabel: 'Сурагч',
    subj_qualityLabel: 'Чанар',
    subj_highestLabel: 'Хамгийн өндөр',
    subj_lowestLabel: 'Хамгийн бага',
    subj_detailsArrow: '▼ Дэлгэрэнгүй',
    subj_studentsCountLabel: '{count} сурагчийн дүнгийн дэлгэрэнгүй мэдээлэл',
    subj_avgLabel: 'Дундаж',
    subj_highLabel: 'Өндөр',
    subj_lowLabel: 'Бага',
    subj_scoreByComponentTitle: 'Сурагч бүрийн оноо (бүрэлдэхүүнээр)',
    subj_rankingTitle: 'Сурагчдын жагсаалт (өндрөөс бага)',

    // ── ChangePassword ────────────────────────────────────────
    cp_sideTitle: 'Аюулгүй байдал',
    cp_sideText: 'Нууц үгийг тогтмол солих нь таны бүртгэлийн аюулгүй байдлыг хангана. Хамгийн багадаа 6 тэмдэгт ашиглана уу.',
    cp_pillEncryption: '🔐 bcrypt шифрлэлт',
    cp_pillJwt: '🛡️ JWT токен',
    cp_subtitle: 'Имэйл болон нууц үгийг оруулна уу',
    cp_currentPassword: 'Одоогийн нууц үг',
    cp_currentPasswordPlaceholder: 'Одоогийн нууц үгийг оруулна уу',
    cp_newPassword: 'Шинэ нууц үг',
    cp_confirmNewPassword: 'Шинэ нууц үг давтах',
    cp_confirmNewPasswordPlaceholder: 'Шинэ нууц үгийг дахин оруулна уу',
    cp_backToLogin: 'Нэвтрэх хуудас руу буцах',
    cp_mismatchError: 'Шинэ нууц үг таарахгүй байна',
    cp_tooShortError: 'Шинэ нууц үг дор хаяж 6 тэмдэгт байх ёстой',
    cp_successMsg: 'Нууц үг амжилттай солигдлоо!',
    cp_changeError: 'Нууц үг солиход алдаа гарлаа',

    // ── ManageTeachers ────────────────────────────────────────
    mt_title: 'Хэрэглэгч удирдах',
    mt_subtitle: 'Багш болон админ бүртгэлийг удирдах (зөвхөн админ)',
    mt_fetchError: 'Хэрэглэгчид авахад алдаа гарлаа',
    mt_addedToast: '{name} амжилттай нэмэгдлээ',
    mt_deleteConfirm: '"{name}"-г устгах уу?',
    mt_deletedToast: '{name} устгагдлаа',
    mt_deleteError: 'Устгахад алдаа гарлаа',
    mt_addNewUser: 'Шинэ хэрэглэгч нэмэх',
    mt_username: 'Хэрэглэгчийн нэр',
    mt_role: 'Эрх',
    mt_adding: 'Нэмж байна...',
    mt_addUserBtn: '+ Хэрэглэгч нэмэх',
    mt_userListTitle: 'Хэрэглэгчдийн жагсаалт ({count})',
    mt_noUsers: 'Хэрэглэгч байхгүй байна',
    mt_thRegistered: 'Бүртгэгдсэн',

    // ── Profile ───────────────────────────────────────────────
    profile_title: 'Профайл',
    profile_subtitle: 'Хэрэглэгчийн мэдээлэл болон зураг удирдах',
    profile_fileTooLarge: 'Файлын хэмжээ 5MB-аас хэтэрч байна',
    profile_choosePhoto: 'Зураг сонгоно уу',
    profile_updated: 'Профайл зураг шинэчлэгдлээ',
    profile_uploadError: 'Зураг оруулахад алдаа гарлаа',
    profile_newPhotoSelected: 'Шинэ зураг сонгогдсон. Хадгалахын тулд доорх товч дарна уу.',
    profile_savePhoto: 'Зураг хадгалах',
    profile_changePhoto: 'Зураг солих',
    profile_permTitle: 'Эрхийн мэдээлэл',
    profile_adminPerm1: 'Бүх ангийн сурагчдыг харах боломжтой',
    profile_adminPerm2: 'Бүх сурагчийн дүн засварлах боломжтой',
    profile_adminPerm3: 'Сурагч устгах боломжтой',
    profile_adminPerm4: 'Бүх хэрэглэгчийн мэдээллийг харах боломжтой',
    profile_teacherPerm1: 'Өөрийн бүртгэсэн сурагчдыг харах боломжтой',
    profile_teacherPerm2: 'Өөрийн сурагчдын дүн засварлах боломжтой',
    profile_teacherPerm3: 'Бусад багшийн сурагчийн мэдээлэлд хандах боломжгүй',

    // ── Register ──────────────────────────────────────────────
    reg_sideTitle: 'Шинэ бүртгэл үүсгэх',
    reg_sideText: 'Багш, захирал болон бусад ажилтнууд системд бүртгүүлж сурагчдын дүнг удирдах боломжтой.',
    reg_pillFree: '✅ Үнэгүй',
    reg_pillEncrypted: '🔐 Шифрлэлттэй',
    reg_pillResponsive: '📱 Responsive',
    reg_subtitle: 'Мэдээллээ оруулж шинэ бүртгэл үүсгэнэ үү',
    reg_confirmPassword: 'Нууц үг давтах',
    reg_confirmPasswordPlaceholder: 'Нууц үгийг дахин оруулна уу',
    reg_registering: 'Бүртгэж байна...',
    reg_orPlain: 'эсвэл',
    reg_haveAccount: 'Бүртгэлтэй юу?',
    reg_passwordMismatch: 'Нууц үг таарахгүй байна',
    reg_tooShortError: 'Нууц үг дор хаяж 6 тэмдэгт байх ёстой',
    reg_registerError: 'Бүртгэлд алдаа гарлаа',
    reg_googleRegisterFail: 'Google бүртгэл амжилтгүй болсон',

    // ── StudentGrades ─────────────────────────────────────────
    sg_myGrades: 'Миний дүн',
    sg_classSuffix: '{class} анги',
    sg_avgScoreLabel: 'Дундаж оноо · {letter}',
    sg_highScore: 'Өндөр оноо',
    sg_lowScore: 'Бага оноо',
    sg_avgScoreAllCaps: 'ДУНДАЖ ОНОО',
    sg_chartTitle: 'Хичээл тус бүрийн оноо',
    sg_tableTitle: 'Дүнгийн хүснэгт',
    sg_distTitle: 'Үсгэн дүнгийн тархалт',
    sg_footerNote: 'Дүн буруу байвал багшдаа хандана уу.',
    sg_noData: 'Мэдээлэл олдсонгүй.',
    sg_backToLogin: '← Нэвтрэх хуудас руу буцах',

    // ── StudentProfile ────────────────────────────────────────
    sp_subtitle: 'Сурагчийн хувийн мэдээлэл',
    sp_backToGrades: '← Дүн харах',
    sp_avgShort: 'Дундаж · {letter}',
    sp_subjectsCountLabel: 'Хичээл',
    sp_letterGradeLabel: 'Үсгэн дүн',
    sp_distTitle: 'Дүнгийн тархалт',

    // ── PasswordInput ─────────────────────────────────────────
    pwShow: 'Нууц үг харуулах',
    pwHide: 'Нууц үг нуух',
  },
  en: {
    // ── Shared / nav ──────────────────────────────────────────
    dashboard: 'Dashboard',
    subjects: 'Subjects',
    addStudent: 'Add student',
    manageTeachers: 'Manage teachers',
    password: 'Password',
    changePassword: 'Change password',
    logout: 'Log out',
    menu: 'Menu',
    appName: 'School Gradebook',
    appFullName: 'School Gradebook System',
    appSubtitle: 'General education school',
    login: 'Log in',
    teacherLogin: 'Teacher login',
    studentGrades: 'Student grades',
    welcome: 'Welcome!',
    loginHint: 'Enter your email and password',
    email: 'Email address',
    passwordLabel: 'Password',
    loggingIn: 'Logging in...',
    registerPrompt: "Don't have an account?",
    register: 'Register',
    orGoogle: 'or continue with Google',
    studentLoginHint: 'Get your login details from your teacher',
    loginError: 'Unable to log in',
    googleError: 'Google sign-in failed',
    footer: 'All rights reserved',
    langToggleLabel: 'Change language',
    loginSideText: 'Student grade tracking system. Organize by class, view grades and see them visualized in charts.',
    pillGrades: 'Grade tracking',
    pillCharts: 'Charts',
    pillByClass: 'By class',
    pillSecure: 'Secure',
    sideCopyright: '© 2024 School System',

    // ── Common / reused ───────────────────────────────────────
    back: 'Back',
    backArrow: '← Back',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving...',
    delete: 'Delete',
    edit: 'Edit',
    details: 'Details',
    loadingData: 'Loading data...',
    subjectLabel: 'Subject',
    totalLabel: 'Total',
    letterLabel: 'Letter',
    classLabel: 'Class',
    allOption: 'All',
    nameLabel: 'Name',
    printLabel: 'Print',
    genericError: 'An error occurred',
    roleAdmin: 'Admin',
    roleTeacher: 'Teacher',
    semesterOf: 'Semester {semester}',
    thExam1: 'E1',
    thExam2: 'E2',
    thAttendance: 'Att',
    thIndependent: 'Ind',
    exam1Full: 'Exam 1',
    exam2Full: 'Exam 2',
    attendanceFull: 'Attendance',
    independentFull: 'Independent work',
    subjectsCountUnit: 'subjects',
    studentsCountUnit: 'students',
    gradeExcellent: 'Excellent',
    gradeGood: 'Good',
    gradeAverage: 'Average',
    gradeFail: 'Failing',

    // ── Dashboard ─────────────────────────────────────────────
    dash_subtitle: 'View student grades and statistics',
    dash_totalStudents: 'Total students',
    dash_avgScore: 'Average score',
    dash_successRate: 'Success rate',
    dash_warning: 'Warning (below 60)',
    dash_searchPlaceholder: 'Search by name...',
    dash_classFilter: 'Class:',
    dash_yearFilter: 'Year:',
    dash_semesterFilter: 'Semester:',
    dash_semester1: 'Semester 1',
    dash_semester2: 'Semester 2',
    dash_totalPill: 'Total:',
    dash_template: 'Template',
    dash_importExcel: 'Import Excel',
    dash_qualityChartTitle: 'Subject quality (% of students scoring ≥75)',
    dash_quality: 'Quality',
    dash_noResultsFor: 'No student found named "{search}"',
    dash_noStudents: 'No students registered yet',
    dash_tryOtherSearch: 'Try searching a different name.',
    dash_addHint: 'Click "Add student" above to register a new student.',
    dash_atRiskBanner: 'Below passing — warning',
    dash_prevPage: '← Previous',
    dash_nextPage: 'Next →',
    dash_deleteConfirm: 'Delete "{name}"?',
    dash_deletedToast: '{name} deleted',
    dash_gradeSaved: 'Grades saved successfully',
    dash_saveError: 'Error saving',
    dash_templateDownloaded: 'Template file downloaded',
    dash_noDataInFile: 'No data found in file',
    dash_importedCount: '{count} students added',
    dash_importFailCount: ', {count} failed: {error}',
    dash_importNoneAdded: 'Nothing added — {error}',
    dash_fileReadError: 'Error reading file',
    dash_excelDownloaded: 'Excel file downloaded',
    modal_subjectNameRequired: 'Please enter a subject name',
    modal_subjectExists: '"{name}" already exists',
    modal_newSubjectPlaceholder: 'Subject name',

    // ── AddStudent ────────────────────────────────────────────
    add_pageTitle: 'Register new student',
    add_pageSubtitle: 'Enter student information and subject grades',
    add_photo: 'Photo',
    add_addPhoto: 'Add photo',
    add_uploading: 'Uploading...',
    add_lastName: 'Last name',
    add_firstName: 'First name',
    add_academicYear: 'Academic year',
    add_semester: 'Semester',
    add_gmail: 'Gmail address',
    add_optional: '(optional)',
    add_loginPassword: 'Login password',
    add_minChars: 'At least 6 characters',
    add_fullName: 'Full name:',
    add_gradesTitle: 'Subject grades',
    add_avgTotalScore: 'Average total score:',
    add_newSubjectPlaceholder: 'New subject name...',
    add_addSubjectBtn: '+ Add subject',
    add_registerBtn: 'Register student',
    add_subjectAlreadyAdded: 'This subject has already been added',
    add_fileTooLarge: 'File exceeds 5MB',
    add_photoReady: 'Photo ready',
    add_photoUploadError: 'Error uploading photo',
    add_requiredFields: 'Please enter last name, first name and class!',
    add_atLeastOneSubject: 'At least one subject must be added',
    add_registeredToast: '{name} registered successfully',
    add_registerError: 'Error registering student',

    // ── StudentDetail ─────────────────────────────────────────
    detail_fetchError: 'Error fetching student information',
    detail_loading: 'Loading student information...',
    detail_deleteConfirm: 'Are you sure you want to delete "{name}"? This action cannot be undone.',
    detail_classPrefix: 'Class:',
    detail_avgTotal: 'Overall average',
    detail_chartTitle: 'Total score by subject',
    detail_gradesDetailTitle: 'Grade details',
    detail_savingShort: 'Saving...',
    detail_teacherSign: 'Teacher signature: ___________',
    detail_date: 'Date:',
    detail_printSchoolName: 'SCHOOL GRADEBOOK SYSTEM',
    detail_printReportTitle: 'GRADE REPORT',
    detail_printAvg: 'Average grade:',
    detail_printYear: 'Academic year:',
    detail_printAvgFooter: 'Overall average score:',

    // ── SubjectDashboard ──────────────────────────────────────
    subj_subtitle: 'Grade statistics and chart comparison per subject',
    subj_totalSubjects: 'Total subjects',
    subj_totalEntries: 'Total grade entries',
    subj_highestAvg: 'Highest average',
    subj_lowestAvg: 'Lowest average',
    subj_sortBy: 'Sort by:',
    subj_sortAvg: 'By average',
    subj_sortName: 'By name',
    subj_sortCount: 'By student count',
    subj_allClasses: 'All classes',
    subj_noData: 'No subject data available',
    subj_noDataHint: 'First add student and grade information.',
    subj_excellentTitle: 'Excellent (≥90): {count}',
    subj_goodTitle: 'Good (75-89): {count}',
    subj_belowTitle: 'Below (<75): {count}',
    subj_excellentLabel: 'excellent',
    subj_goodLabel: 'good',
    subj_belowLabel: 'below',
    subj_studentsLabel: 'Students',
    subj_qualityLabel: 'Quality',
    subj_highestLabel: 'Highest',
    subj_lowestLabel: 'Lowest',
    subj_detailsArrow: '▼ Details',
    subj_studentsCountLabel: 'Detailed grade information for {count} students',
    subj_avgLabel: 'Average',
    subj_highLabel: 'High',
    subj_lowLabel: 'Low',
    subj_scoreByComponentTitle: 'Score per student (by component)',
    subj_rankingTitle: 'Student ranking (highest to lowest)',

    // ── ChangePassword ────────────────────────────────────────
    cp_sideTitle: 'Security',
    cp_sideText: 'Changing your password regularly keeps your account secure. Use at least 6 characters.',
    cp_pillEncryption: '🔐 bcrypt encryption',
    cp_pillJwt: '🛡️ JWT token',
    cp_subtitle: 'Enter your email and password',
    cp_currentPassword: 'Current password',
    cp_currentPasswordPlaceholder: 'Enter your current password',
    cp_newPassword: 'New password',
    cp_confirmNewPassword: 'Confirm new password',
    cp_confirmNewPasswordPlaceholder: 'Re-enter your new password',
    cp_backToLogin: 'Back to login page',
    cp_mismatchError: 'New passwords do not match',
    cp_tooShortError: 'New password must be at least 6 characters',
    cp_successMsg: 'Password changed successfully!',
    cp_changeError: 'Error changing password',

    // ── ManageTeachers ────────────────────────────────────────
    mt_title: 'Manage users',
    mt_subtitle: 'Manage teacher and admin accounts (admin only)',
    mt_fetchError: 'Error fetching users',
    mt_addedToast: '{name} added successfully',
    mt_deleteConfirm: 'Delete "{name}"?',
    mt_deletedToast: '{name} deleted',
    mt_deleteError: 'Error deleting',
    mt_addNewUser: 'Add new user',
    mt_username: 'Username',
    mt_role: 'Role',
    mt_adding: 'Adding...',
    mt_addUserBtn: '+ Add user',
    mt_userListTitle: 'User list ({count})',
    mt_noUsers: 'No users',
    mt_thRegistered: 'Registered',

    // ── Profile ───────────────────────────────────────────────
    profile_title: 'Profile',
    profile_subtitle: 'Manage user information and photo',
    profile_fileTooLarge: 'File size exceeds 5MB',
    profile_choosePhoto: 'Please choose a photo',
    profile_updated: 'Profile photo updated',
    profile_uploadError: 'Error uploading photo',
    profile_newPhotoSelected: 'New photo selected. Click the button below to save.',
    profile_savePhoto: 'Save photo',
    profile_changePhoto: 'Change photo',
    profile_permTitle: 'Permissions',
    profile_adminPerm1: 'Can view students in all classes',
    profile_adminPerm2: 'Can edit grades for all students',
    profile_adminPerm3: 'Can delete students',
    profile_adminPerm4: 'Can view all user information',
    profile_teacherPerm1: 'Can view students they registered',
    profile_teacherPerm2: 'Can edit grades for their own students',
    profile_teacherPerm3: "Cannot access other teachers' student information",

    // ── Register ──────────────────────────────────────────────
    reg_sideTitle: 'Create a new account',
    reg_sideText: 'Teachers, principals and other staff can register to manage student grades.',
    reg_pillFree: '✅ Free',
    reg_pillEncrypted: '🔐 Encrypted',
    reg_pillResponsive: '📱 Responsive',
    reg_subtitle: 'Enter your information to create a new account',
    reg_confirmPassword: 'Confirm password',
    reg_confirmPasswordPlaceholder: 'Re-enter your password',
    reg_registering: 'Registering...',
    reg_orPlain: 'or',
    reg_haveAccount: 'Already have an account?',
    reg_passwordMismatch: 'Passwords do not match',
    reg_tooShortError: 'Password must be at least 6 characters',
    reg_registerError: 'Error registering',
    reg_googleRegisterFail: 'Google registration failed',

    // ── StudentGrades ─────────────────────────────────────────
    sg_myGrades: 'My grades',
    sg_classSuffix: 'Class {class}',
    sg_avgScoreLabel: 'Average score · {letter}',
    sg_highScore: 'Highest score',
    sg_lowScore: 'Lowest score',
    sg_avgScoreAllCaps: 'AVERAGE SCORE',
    sg_chartTitle: 'Score by subject',
    sg_tableTitle: 'Grade table',
    sg_distTitle: 'Letter grade distribution',
    sg_footerNote: 'If a grade seems incorrect, please contact your teacher.',
    sg_noData: 'No data found.',
    sg_backToLogin: '← Back to login page',

    // ── StudentProfile ────────────────────────────────────────
    sp_subtitle: 'Student personal information',
    sp_backToGrades: '← View grades',
    sp_avgShort: 'Average · {letter}',
    sp_subjectsCountLabel: 'Subjects',
    sp_letterGradeLabel: 'Letter grade',
    sp_distTitle: 'Grade distribution',

    // ── PasswordInput ─────────────────────────────────────────
    pwShow: 'Show password',
    pwHide: 'Hide password',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('ebs_language') || 'mn');

  useEffect(() => {
    localStorage.setItem('ebs_language', language);
    document.documentElement.lang = language;
    document.title = language === 'en' ? 'School Gradebook' : 'ЕБС Дүн Бүртгэлийн Систем';
  }, [language]);

  const toggleLanguage = () => setLanguage(current => current === 'mn' ? 'en' : 'mn');

  const t = (key, vars) => {
    let str = translations[language][key] ?? translations.mn[key] ?? key;
    if (vars) {
      for (const [k, v] of Object.entries(vars)) {
        str = str.replaceAll(`{${k}}`, v);
      }
    }
    return str;
  };

  return <LanguageContext.Provider value={{ language, toggleLanguage, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
